Update Player.java, and simplified functions
CSC207-2022F-UofT/course-project-rogue pull request #2
Opened 2022-10-26 04:29 UTC by stalight

Jillian should especially check because I left some notes for some functions which you may need to take reference of when implementing items

2022-10-26 04:50 UTC, littlepeach17 submitted a review, later dismissed
Looks good and yep I've taken note about the Item stuff

2022-10-31 15:17 UTC, littlepeach17 approved these changes
Implements Triggerable is not needed for subclasses of Event, because Event already implements Triggerable

2022-10-31 15:38 UTC, jchenDDD approved these changes

2022-10-31 15:38 UTC, UTDQi approved these changes

2022-11-01 19:52 UTC, villanueva-j commented
I have some comments and questions we can discuss on the discord.

for Player class:
- Since we already discussed creating an inventory class, for "weapon" and "armor" in inventory, I suggest we create specific weapon and armor classes, and set the type of those parameters to each respective class (ex: Weapon weapon, Armor armor). That way we have a way to prevent armor equipment from being assigned to weapon and vice versa.
- type difference for method getPlayerLocation vs. location type (method return hashmap<Character, Integer> but location is of type <String, Integer>)

for Player constructor: 
- the code can be made cleaner by creating an inventory class like you said 
- Does Player always start with same base stats? If so, we can overload the constructor to have default stats.
- Does Player start with any equipment? then for inventory class, we can have a constructor that does not assign anything to weapon and armor and one that does to allow for extension for if Players are given a choice of weapon

for Events:
- looks good. Maybe if we have time we can add some sort of cute text that is returned when a player triggers WallEvent like "Ouch, that's a wall". 
 
You should add javadoc for all your methods so it is clear what each does. Other than that looks good!

2022-11-03 03:04 UTC, littlepeach17 approved these changes

2022-11-04 00:25 UTC, villanueva-j commented on src/main/java/entity/CollectibleInventory.java
> +        Collectible collectible = getCollectible(collectibyType);
typo here

2022-11-04 00:55 UTC, villanueva-j requested changes
Typo fix and add in javadoc

Some methods you put javadoc in but you put it after method declaration, it needs to go before

2022-11-04 02:22 UTC, jchenDDD submitted a review, later dismissed

2022-11-04 02:27 UTC, littlepeach17 submitted a review, later dismissed
documentation looks nice

2022-11-04 03:38 UTC, stalight commented
I changed the Interface
"Triggerable" to "Enterable"
and moved
"Trigger" to Event parent class

2022-11-04 03:52 UTC, merged